config/routes.rb
Rails.application.routes.draw do
  resources :corps do
    collection do
      get :export
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/corp.rb
class Corp
  include Mongoid::Document
  field :name, type: String
  field :no, type: String
  field :legal_person, type: String
  field :area, type: String
  field :address, type: String
  field :corp_type, type: String
  field :phone, type: String
  field :created_at, type: DateTime
  field :email, type: String
  field :register_amount, type: String
  field :regcap_cur, type: String
  field :est_date, type: String
  field :regcaption, type: String
  field :doc_count, type: Integer
  field :pension_insurance, type: Integer
  field :tax_amount, type: String
  field :bid_count, type: Integer
  field :d101a, type: Boolean
  field :d101t, type: Boolean
  field :d110a, type: Boolean
  field :d110t, type: Boolean

  def scopes
    result = []
    result << '房建特级' if d101t
    result << '房建一级' if d101a
    result << '市政特级' if d110t
    result << '市政一级' if d110a
    result.join('/')
  end
end

app/controllers/corps_controller.rb
class CorpsController < ApplicationController
  before_action :set_corp, only: [:show, :edit, :update, :destroy]
  before_action :search_crops, only: [:index, :export]

  # GET /corps
  # GET /corps.json
  def index
    @provinces = Province.all
    @corps = @corps.page(params[:page]).per(50)
  end

  # GET /corps/1
  # GET /corps/1.json
  def show
    blacks = BlackListItem.data.map(&:values).to_h
    break_items = BreakItem.data.map(&:values).to_h
    punishe_list = AdministrativePunish.data.map(&:values).to_h
    manage_list = AbnormalOperation.data.map(&:values).to_h
    bid_list = BidItem.data.map(&:values).to_h

    black_lists = {}
    # 黑名单
    blacks.each do |k, v|
      black_lists[k] ||= 0
      black_lists[k] += v
    end
    # 行政处罚
    punishe_list.each do |k, v|
      black_lists[k] ||= 0
      black_lists[k] += v
    end
    # 经营异常
    manage_list.each do |k, v|
      black_lists[k] ||= 0
      black_lists[k] += v
    end

    @blacklist_count = black_lists[@corp.no] || 0
    @black_count = blacks[@corp.no] || 0
    @punishe_count = punishe_list[@corp.no] || 0
    @manage_risk_count = manage_list[@corp.no] || 0
    @law_rist_count = @corp.doc_count
    @bid_count = bid_list[@corp.no] || 0
    @break_count = break_items[@corp.no] || 0
  end

  def export
    file_path = Rails.root.join('public', 'exports', "export-#{Time.now.to_i}.xls")
    book = Spreadsheet::Workbook.new
    sheet = book.create_worksheet
    sheet.row(0).concat %w{企业名称 企业统一信用代码 法人 邮箱 电话 注册资本 成立日期 黑名单数量 行政处罚 工商异常数量 严重违法 法院诉讼数量 招投标数据 纳税额 公司社保缴纳人数}

    blacks = BlackListItem.data.map(&:values).to_h
    break_items = BreakItem.data.map(&:values).to_h
    punishe_list = AdministrativePunish.data.map(&:values).to_h
    manage_list = AbnormalOperation.data.map(&:values).to_h
    bid_list = BidItem.data.map(&:values).to_h

    black_lists = {}
    # 黑名单
    blacks.each do |k, v|
      black_lists[k] ||= 0
      black_lists[k] += v
    end
    # 行政处罚
    punishe_list.each do |k, v|
      black_lists[k] ||= 0
      black_lists[k] += v
    end
    # 经营异常
    manage_list.each do |k, v|
      black_lists[k] ||= 0
      black_lists[k] += v
    end

    @corps.each_with_index do |corp, index|
      blacklist_count = black_lists[corp.no] || 0
      black_count = blacks[corp.no] || 0
      punishe_count = punishe_list[corp.no] || 0
      manage_risk_count = manage_list[corp.no] || 0
      law_rist_count = corp.doc_count
      bid_count = bid_list[corp.no] || 0
      row = sheet.row(index + 1)
      row.push corp.name
      row.push corp.no
      row.push corp.legal_person
      row.push corp.email
      row.push corp.phone
      row.push corp.regcaption
      row.push corp.est_date
      row.push blacklist_count
      row.push punishe_count
      row.push manage_risk_count
      row.push black_count
      row.push law_rist_count
      row.push bid_count
      row.push '暂无数据'
      row.push '暂无数据'
    end

    book.write file_path
    send_file file_path, type: 'text/plain', disposition: 'attachment'
  end

  # GET /corps/new
  def new
    @corp = Corp.new
  end

  # GET /corps/1/edit
  def edit
  end

  # POST /corps
  # POST /corps.json
  def create
    @corp = Corp.new(corp_params)

    respond_to do |format|
      if @corp.save
        format.html { redirect_to @corp, notice: 'Corp was successfully created.' }
        format.json { render :show, status: :created, location: @corp }
      else
        format.html { render :new }
        format.json { render json: @corp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corps/1
  # PATCH/PUT /corps/1.json
  def update
    respond_to do |format|
      if @corp.update(corp_params)
        format.html { redirect_to @corp, notice: 'Corp was successfully updated.' }
        format.json { render :show, status: :ok, location: @corp }
      else
        format.html { render :edit }
        format.json { render json: @corp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corps/1
  # DELETE /corps/1.json
  def destroy
    @corp.destroy
    respond_to do |format|
      format.html { redirect_to corps_url, notice: 'Corp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corp
      @corp = Corp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corp_params
      params.require(:corp).permit(:name, :no)
    end

    def search_crops
      if params[:form].blank?
        params[:d101t] = true
        params[:d101a] = true
        params[:d110a] = true
        params[:blacklist] = true
        params[:manage] = true
        params[:bid] = true
        params[:law] = true
        params[:tax] = true
        params[:shixin] = true
      end
      @corps = Corp.all
      scopes = []
      scopes << { d101t: true } if params[:d101t]
      scopes << { d101a: true } if params[:d101a]
      scopes << { d110a: true } if params[:d110a]
      scopes = {no: 'unknown'} if scopes.blank?
      @corps = @corps.or(scopes)
      @corps = @corps.where(name: /#{params[:corp_name]}/) if params[:corp_name].present?
      @corps = @corps.where(area: params[:province]) if params[:province].present?

      if params[:blacklist]
        # 黑名单
        black_lists = {}
        BlackListItem.data.each do |item|
          black_lists[item['_id']] ||= 0
          black_lists[item['_id']] += item['count']
        end
        # 行政处罚
        AdministrativePunish.data.each do |item|
          black_lists[item['_id']] ||= 0
          black_lists[item['_id']] += item['count']
        end
        # 经营异常
        AbnormalOperation.data.each do |item|
          black_lists[item['_id']] ||= 0
          black_lists[item['_id']] += item['count']
        end
        nos = black_lists.select{|k, v| v >= 10 }.keys
        Rails.logger.info(nos)
        @corps = @corps.where(no: {'$nin': nos })
      end

      # 工商经营异常（即经营异常大于0）
      if params[:manage]
        nos = AbnormalOperation.data.select {|item| item['count'] > 0 }.map { |item| item['_id'] }
        @corps = @corps.where(no: { '$in': nos})
      end

      # 法院诉讼大于20个
      @corps = @corps.where(doc_count: { '$gt': 20 }) if params[:law]
      @corps = @corps.where(no: { '$nin': BidItem.suit_nos }) if params[:bid]

      if params[:shixin]
        nos = BreakItem.data.select {|item| item['count'] <= 10 }.map { |item| item['_id'] }
        @corps = @corps.where(no: { '$in': nos})
      end
    end
end

app/helpers/corps_helper.rb
module CorpsHelper
end

app/views/corps/_detail.html.erb
<tr class="detail">
  <td colspan=9 align="left">
    <table width='100%'  class="detail-table">
      <tr>
        <th width="15%">企业名称</th>
        <td><%= @corp.name %></td>
        <th width="15%">统一社会信用代码</th>
        <td><%= @corp.no %></td>
        <th width="15%">法人代表</th>
        <td><%= @corp.legal_person %></td>
        <td></td>
      </tr>
      <tr>
        <th>企业资质资格列表</th>
        <td><%= @corp.scopes %></td>
        <th>股东数量</th>
        <td><%= Shareholder.where(corp_no: @corp.no).count %></td>
        <th>企业经营地址</th>
        <td><%= @corp.address %></td>
      </tr>
      <tr>
        <th>注册地</th>
        <td><%= @corp.address %></td>
        <th>注册资本</th>
        <td><%= @corp.regcaption %></td>
        <th>企业登记注册类型</th>
        <td><%= @corp.corp_type %></td>
      </tr>
      <tr>
        <th>主要股东</th>
        <td><%= Shareholder.where(corp_no: @corp.no ).map(&:name).join('/') %></td>
        <th>纳税额</th>
        <td>暂无数据</td>
        <th>公司社保缴纳人数</th>
        <td>暂无数据</td>
      </tr>
      <tr>
        <th>成立时间</th>
        <td><%= @corp.est_date %></td>
        <th>邮箱</th>
        <td><%= @corp.email %></td>
        <th>电话</th>
        <td><%= @corp.phone %></td>
      </tr>
      <tr>
        <th>黑名单总量</th>
        <td colspan="3"><%= @blacklist_count %> (行政处罚: <%= @punishe_count %>/经营异常: <%= @manage_risk_count %>/严重违法: <%= @black_count %>)</td>
        <th>失信记录数</th>
        <td><%= @break_count %></td>
      </tr>
      <tr>
        <th>法院诉讼</th>
        <td><%= @law_rist_count %></td>
        <th>半年内招投标数量</th>
        <td><%= @bid_count %></td>
      </tr>
    </table>
  </td>
</tr>

app/views/corps/_form.html.erb
<%= form_with(model: corp, local: true) do |form| %>
  <% if corp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(corp.errors.count, "error") %> prohibited this corp from being saved:</h2>

      <ul>
      <% corp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :no %>
    <%= form.text_field :no %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/corps/edit.html.erb
<h1>Editing Corp</h1>

<%= render 'form', corp: @corp %>

<%= link_to 'Show', @corp %> |
<%= link_to 'Back', corps_path %>

app/views/corps/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">企业查询</li>
  </ol>
</nav>

<%= form_tag '', method: 'get' do %>
  <%= hidden_field_tag :form, true %>
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">企业资质:</label>
    <div class="col-sm-10">
      <div class="form-check form-check-inline">
        <%= check_box_tag 'd101t', true, params[:d101t], class: "form-check-input" %>
        <label class="form-check-label" for="d101t">房建特级</label>
      </div>
      <div class="form-check form-check-inline">
        <%= check_box_tag 'd101a', true, params[:d101a], class: "form-check-input" %>
        <label class="form-check-label" for="d101a">房建一级</label>
      </div>
      <div class="form-check form-check-inline">
        <%= check_box_tag 'd110a', true, params[:d110a], class: "form-check-input" %>
        <label class="form-check-label" for="d110t">市政一级</label>
      </div>
    </div>

    <label for="staticEmail" class="col-sm-2 col-form-label">过滤条件:</label>
    <div class="col-sm-10">
      <div class="form-check">
        <%= check_box_tag 'blacklist', true, params[:blacklist] %>
        <label class="form-check-label" for="blacklist">失信黑名单(行政处罚、经营异常、严重违法)1-10个</label>
      </div>
      <div class="form-check">
        <%= check_box_tag 'manage', true, params[:manage] %>
        <label class="form-check-label" for="manage">工商经营异常</label>
      </div>
      <div class="form-check">
        <%= check_box_tag 'law', true, params[:law] %>
        <label class="form-check-label" for="law">法院诉讼大于20</label>
      </div>
      <div class="form-check">
        <%= check_box_tag 'bid', true, params[:bid] %>
        <label class="form-check-label" for="bid">近两年中标数量小于3个或半年内没有招投标</label>
      </div>
      <div class="form-check">
        <%= check_box_tag 'tax', true, params[:tax] %>
        <label class="form-check-label" for="tax">近两年纳税额小于1000万</label>
      </div>
      <div class="form-check">
        <%= check_box_tag 'shixin', true, params[:shixin] %>
        <label class="form-check-label" for="shixin">失信信息1-10个</label>
      </div>
    </div>
    <label for="staticEmail" class="col-sm-2 col-form-label">企业名称:</label>
    <div class="col-sm-10">
      <div class="form-check form-check-inline">
        <%= text_field_tag 'corp_name', params[:corp_name], class: "form-control" %>
      </div>
    </div>
    <label for="staticEmail" class="col-sm-2 col-form-label">注册地址:</label>
    <div class="col-sm-10">
      <div class="form-check form-check-inline">
        <%= select_tag 'province',
          options_from_collection_for_select(@provinces, "name", "name", params[:province]),
          include_blank: "选择省份" %>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-12">
      <%= submit_tag '查询', class: "btn btn-primary" %>
      <%= button_tag '导出', class: "btn btn-primary", id: 'export' %>
    </div>
  </div>
<% end %>

<div class="row">
  
  <div class="col-sm-12 text-right">
    总记录数: <%= @corps.total_count %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>序号</th>
      <th>企业名称</th>
      <th>信用代码</th>
      <th>注册资本</th>
      <th>成立时间</th>
      <th>法人</th>
      <th>注册地</th>
    </tr>
  </thead>

  <tbody>
    <% @corps.each_with_index do |corp, index| %>
      <tr id="item_<%= corp.id %>">
        <td><%= (@corps.current_page - 1) * @corps.current_per_page + index + 1 %></td>
        <td><%= link_to corp.name, corp, remote: true %></td>
        <td><%= corp.no %></td>
        <td><%= corp.regcaption.to_i %></td>
        <td><%= corp.est_date %></td>
        <td><%= corp.legal_person %></td>
        <td><%= corp.area %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @corps %>

<script>
$(function() {
  $("#export").click(function() {
    window.open("<%= export_corps_path %>?" + $("form").serialize());
  });
  $("tr td a").click(function() {
    if($(this).hasClass('current')) {
      $(this).parent().parent().next().remove();
      $(this).removeClass('current');
      return false;
    }
  })
});
</script>

app/views/corps/new.html.erb
<h1>New Corp</h1>

<%= render 'form', corp: @corp %>

<%= link_to 'Back', corps_path %>

app/views/corps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @corp.name %>
</p>

<p>
  <strong>No:</strong>
  <%= @corp.no %>
</p>

<%= link_to 'Edit', edit_corp_path(@corp) %> |
<%= link_to 'Back', corps_path %>

app/views/corps/show.js.erb
$(".detail").remove();
$("#item_<%= @corp.id %>").after("<%= j render('detail') %>")
$("#item_<%= @corp.id %> a").addClass('current');